name: msavings_notes
description: "A professional AMOLED black Flutter savings and notes app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.27.0
  cloud_firestore: ^4.15.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  image_path: "app_icon.png.jpg"

flutter:
  uses-material-design: true
